"""actors movies assignements

Revision ID: 04b281a110fc
Revises: ddf3e9aa4add
Create Date: 2020-05-02 11:46:11.933462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b281a110fc'
down_revision = 'ddf3e9aa4add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors_movies', sa.Column('actor_id', sa.Integer(), nullable=False))
    op.add_column('actors_movies', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.drop_constraint('actors_movies_actor_fkey', 'actors_movies', type_='foreignkey')
    op.drop_constraint('actors_movies_movie_fkey', 'actors_movies', type_='foreignkey')
    op.create_foreign_key(None, 'actors_movies', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'actors_movies', 'actors', ['actor_id'], ['id'])
    op.drop_column('actors_movies', 'actor')
    op.drop_column('actors_movies', 'movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors_movies', sa.Column('movie', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('actors_movies', sa.Column('actor', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'actors_movies', type_='foreignkey')
    op.drop_constraint(None, 'actors_movies', type_='foreignkey')
    op.create_foreign_key('actors_movies_movie_fkey', 'actors_movies', 'movies', ['movie'], ['title'])
    op.create_foreign_key('actors_movies_actor_fkey', 'actors_movies', 'actors', ['actor'], ['name'])
    op.drop_column('actors_movies', 'movie_id')
    op.drop_column('actors_movies', 'actor_id')
    # ### end Alembic commands ###
