"""enable saving datetimes with timezones

Revision ID: 1bd9776b5b8d
Revises: 3e2406c9695a
Create Date: 2020-05-01 15:33:42.349858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd9776b5b8d'
down_revision = '3e2406c9695a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
