"""first migration, canonic aproach [LTS]

Revision ID: b21eddc2d3f5
Revises: 
Create Date: 2020-05-01 11:06:17.122816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21eddc2d3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('actors_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('movie', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['actor'], ['actors.name'], ),
    sa.ForeignKeyConstraint(['movie'], ['movies.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors_movies')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
